---
- hosts: all
  become: true

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted

  tasks:
    - name: Update SSH configuration
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
        state: present
        validate: 'sshd -t -f %s'
        backup: true
      with_items:
        - regexp: '^#?PasswordAuthentication'
          line: 'PasswordAuthentication no'
        - regexp: '^#?PermitRootLogin'
          line: 'PermitRootLogin no'
      notify: Restart ssh

    - name: Add user manoli
      ansible.builtin.user:
        name: manoli
        state: present

    - name: Enable passwordless sudo for user manoli
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        regexp: '^manoli'
        line: 'manoli ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'
        backup: true

    - name: Remove unused packages
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-django
          - python3-pymysql
          - mariadb-server
          - apache2
        state: absent
        purge: true

    - name: Set file permissions
      ansible.builtin.file:
        path: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'

    - name: Install unattended-upgrades package
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present

    - name: Copy unattended-upgrades configuration files
      ansible.builtin.template:
        src: 'templates/{{ item }}.j2'
        dest: '/etc/apt/apt.conf.d/{{ item }}'
        owner: root
        group: root
        mode: 0644
      with_items:
        - 20auto-upgrades
        - 50unattended-upgrades

    - name: Install firewalld
      ansible.builtin.apt:
        name: firewalld
        state: present

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Configure ports in firewalld
      ansible.posix.firewalld:
        zone: external
        port: '{{ item.port }}'
        state: '{{ item.state }}'
        permanent: true
        immediate: true
      with_items:
        - port: 22/tcp
          state: enabled
        - port: 80/tcp
          state: enabled
        - port: 123/udp
          state: enabled

    - name: Install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present

    - name: Copy fail2ban configuration file in place
      ansible.builtin.template:
        src: templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644

    - name: Ensure fail2ban is running
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes
