---
- hosts: templates
  become: true

  vars_files:
    - vault.yml

  handlers:
    - name: restart_networking
      ansible.builtin.service:
        name: networking
        state: restarted

  tasks:
    - name: Reset machine-id
      tags: machine_id
      block:
        - name: Make /etc/machine-id a 0-byte file
          community.general.filesize:
            path: /etc/machine-id
            size: 0

        - name: Remove D-Bus machine ID
          ansible.builtin.file:
            path: /var/lib/dbus/machine-id
            state: absent

        - name: Generate new D-Bus machine ID
          ansible.builtin.command:
            cmd: dbus-uuidgen --ensure
            creates: /var/lib/dbus/machine-id

        - name: Initialize machine ID from D-Bus machine ID
          ansible.builtin.command:
            cmd: systemd-machine-id-setup
          register: systemd_machine_id_setup
          changed_when: systemd_machine_id_setup.stderr != ''


    - name: Reset DHCP lease files
      tags: dhcp_lease_files
      block:
        - name: Find DHCP lease files
          ansible.builtin.find:
            paths:
              - /var/lib/dhcp
              - /var/lib/dhclient
          register: dhcp_lease

        - name: Remove DHCP lease files
          ansible.builtin.file:
            path: '{{ item.path }}'
            state: absent
          with_items: '{{ dhcp_lease.files }}'
          notify: restart_networking


    - name: Reset SSH host keys
      tags: ssh_host_keys
      block:
        - name: Find SSH host key files
          ansible.builtin.find:
            paths: /etc/ssh
            patterns: '^ssh_host_.*_key(\.pub)?$'
            use_regex: true
          register: ssh_host_key

        - name: Remove SSH host keys
          ansible.builtin.file:
            path: '{{ item.path }}'
            state: absent
          with_items: '{{ ssh_host_key.files }}'

        - name: Reconfigure openssh-server
          ansible.builtin.command:
            cmd: dpkg-reconfigure openssh-server
          register: openssh_server_recon
          changed_when: '"Creating" in openssh_server_recon.stderr'
