---
- hosts: all

  vars_files:
    - vault.yml

  tasks:
    - name: All Ansible Facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Checkout hostname
      ansible.builtin.debug:
        msg:
          - "ansible_hostname = {{ ansible_hostname }}"
          - "inventory_hostname = {{ inventory_hostname }}"
