---
- hosts: all

  vars_files:
    - vault.yml

  tasks:
    - name: Checkout facts
      ansible.builtin.debug:
        msg:
          - "ansible_hostname = {{ ansible_hostname }}"
          - "inventory_hostname = {{ inventory_hostname }}"
